server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/growth_hr
    username: root
    password: root_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:/com/growthhrapi/dao/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org:
      springframework: WARN
    com:
      growthhrapi:
        dao: DEBUG
